### ISSUE TITLE
Video - Project Management

### ISSUE THREAD

**Issue by Haotzzz** [aryobarzan/UL-SE-2018-g05#33]

**Comment by Haotzzz** [comment]
Script: 
Group 5, Sprint 3 project management video. 
The project management is done using the ZenHub plugin for GitHub. ZenHub lets us manage our GitHub issues in a different but better way, for instance we have the possibility to create Epics and to follow a burndown report. 
Different issues were created for updating our specification from sprint 1 and to continue implementing our variant. For the quality insurance, an issue is created for the graphical user interface. 
Several Epic are created for the deliverables at the end of this sprint 3. Deliverables of this sprint 3 are the project management video which is estimated with 10 story points, the video of the implementation with 8 story points and the video of the Messir requirements specification with 7 story points. The story points are estimated using our experience of the previous sprints. 
The issues left right now are the (…) but these issues will be closed before the end of this sprint. 
Although the group has started to work on their variant one the first week, the burndown chart isn’t showing it because the issues created were to large with an estimated story point of 10, that’s why the graph only started to drop on the last week of this sprint. This is, because issues were not closed until it the work was done. So, for improving the chart of the burndown report, one solution is to create smaller issues with lower story points, so each issue can be close when the work is done. 
Furthermore, the story points estimation for the issues created this sprint were mostly accurate with the time spent work on it. 
For the next and last sprint, the objective is to finish the project. We will work on fixing some minor issues or correcting some minor problems and set up the deliverables of the source files for the Implementation and Messir requirements specification v1.0.

**Comment by aryobarzan** [comment]
- I'd say remove the first point, it's not useful information

- Talk about the branch merges that occurred during this sprint when conflicts arose after 2 project members started working at the same time and attempted to push their changes at the same time.

- Mention the meeting we held to discuss our timeplanning for the rest of the project - that for example: 1) the group was consulted after an error occurred after a push involving the biometric login implementation which changed classes that were used by others 2) the login changes for the coordinator's UI would be implemented in the 4th sprint for both the symmetric and biometric login 3) that the documentation would be a heavy focus in the 4th sprint, 

- For the 5th point, only mention the estimated story points for each issue AND: also mention for each group member how much time they needed in reality - I for example needed double the time that was estimated for the specification of the symmetric login.

- In the last point, mention our main focuses for the final sprint: documentation, database changes, testing of each variant

**Comment by Haotzzz** [comment]
Script: 
Group 5, Sprint 3 project management video. 
- Different issues were created for updating our specification from sprint 1 and to continue implementing our variant. For the quality insurance, an issue is created for the graphical user interface. 
- Several Epic are created for the deliverables at the end of this sprint 3. Deliverables of this sprint 3 are the project management video which is estimated with 10 story points, the video of the implementation with 8 story points and the video of the Messir requirements specification with 7 story points. The story points are estimated using our experience of the previous sprints. 
- The issues left right now are the (…) but these issues will be closed before the end of this sprint. 
- During this sprint some conflicts arose after 2 project members started working at the same time and attempted to push their changes at the same time, so that branch merging was needed. 
- Although the group has started to work on their variant on the first week, the burndown chart isn’t showing it because the issues created were to large with an estimated story point of 10, that’s why the graph only started to drop on the last week of this sprint. This is, because issues were not closed until it the work was done. So, for improving the chart of the burndown report, one solution is to create smaller issues with lower story points, so each issue can be close when the work is done. 
- Additionally, we held some meetings, where we discuss our time planning for the rest of the project. The group was consulted after an error occurred after a push involving the biometric login implementation which changed classes that were used by others, and login changes for the coordinator’s UI would be implemented in the 4th sprint for both the symmetric and biometric login. 
- Furthermore, after getting each member’s feedback, the story points estimation for some issues were not accurate, for instance for the issue of the specification of the symmetric login, the time needed, was double the time that was estimated. 
- For the next and final sprint, our focus goes into the documentation, database changes and testing each variant.
