### ISSUE TITLE
Video - Messir requirements specification v0.2

### ISSUE THREAD

**Issue by Haotzzz** [aryobarzan/UL-SE-2018-g05#34]

**Comment by aryobarzan** [comment]
- Don't explain the messir methodology at this point

Scientific:
- Environment model: amount of changes (the things you've mentioned in the 2nd point)
- use case model: amount of changes
- Concept Model: amount of changes (the things you mentioned in the 4th point, but also you forgot DtEncryptedMessage for me)
- operation model: don't explain the model itself, mention the amount of changes

for the quality side: ?

Technical:
- solely used excalibur for the specification changes
- talk about the shared points of changes (for example actAuthenticated in the environment model and ctState in the concept model)

**Comment by Haotzzz** [comment]
Script: 
The specification of the iCrash system is create using the Messir methodology. Using the Excalibur plugin in Eclipse, we can create the specification according to the Messir methodology. 
- Environment Model specify the actors with their output and input interfaces used to interact with the system. In actor actAuthenticated 4 output interfaces and 2 input interfaces are added. For the actor actAdministrator 5 output interfaces are added. In Actor actComCompany 1 output interface oeAnswer is added.
- Use Case Model specify and illustrate the use case of the actors concerned directly to the system. So, 7 subfunctions are added for the variant authentication using symmetric key or biometric data and for the quality insurance. 4 User Goals are created to specify the ordering constraint of the operations. And, 3 Use-Case-Instance User Goal are created to illustrate the use case if the actors. 
- The Concept Model specify the types structuring the information either used to define the system’s state during its life cycle or exchanged with its environment. In ctAuthenticated an attribute for biometricData and symmetricKey are added. ctQuestion and ctAnswer are create for the quality insurance variant. New datatypes are also created, dtNonce, dtSymmetricKey and dtEncryptedMessage for symmetric key authentication, dtBiometricData for biometric authentication and dtAnswerID, dtAnswerText, dtQuestionID and dtQuestionText for quality insurance. 
- The Operation Model for symmetric key and biometric authentication are added to provide the properties of valid execution for each operation needed to let the user login according the specific authentication methods, so that 4 new added operation are described for the outactAuthenticated and 4 for the ctState.
