### ISSUE TITLE
Video - Implementation 

### ISSUE THREAD

**Issue by Haotzzz** [aryobarzan/UL-SE-2018-g05#35]

**Comment by Haotzzz** [comment]
Script: 
The implementation of the iCrash project is divided in 4 main parts: 
- The specification API part, the client part, server part and the database part. So according to this the Java code is also divided in 4 project, on for each part. 
- The specification API or core hold the environment model and the concept model of the Messir methodology, containing all Actors as an interface with their respective methods or operations, all primary and secondary datatypes according to the Concept Model and the interface of the IcrashSystem. Only the implementation of ComCompany actor is done in this part. 
- The client project holds the graphical user interface of the iCrash system. It provides the physical interface for the actors to interact with the iCrash system. The client side is implemented using MVC (Model View Controller) Pattern. 
- The server project contains mostly the implementation of the interface defined in API or core. So, that the server part is implemented according to the operation model of the Messir methodology. Remote objects will be created and wait until the client invoke methods of those accessible remote objects. 
- The database contains the script to create the iCrash database. 
- The Logger is provided by the Apache Log4J API and the Java RMI API is used since there is an interaction between the client and server side. 
- Variant authentication using symmetric key and biometric data are implemented in the administrator view. Using 3 buttons the admin can switch between different authentication methods. After the choosing one authentication method, the admin can log in using the authentication typical procedure from the specific variant. 
- For the symmetric key authentication, the admin enters his login and a randomly chosen nonce. The systems then return a message including the encrypted nonce, so that the user must enter the login concatenating this encrypted nonce to log into the system. 
- For the biometric authentication, the admin just need to click on the scan button, so that the system can capture the user’s odor in an interval of 10 seconds. If the odor is recognized, so the user is logged in. 
- Variant quality insurance …

**Comment by aryobarzan** [comment]
Scratch most of the points you've listed, as you're just explaining icrash and not what we've done.

Subdivide this into technical and scientific:

Scientific:
- Mention the most changes were in icrashImpl.java
- Mention the shared point of changes: for both biometric and symmetric login, the administrator GUI was further changed, with the addition of new textfields and button for the symmetric login
- The amount of new classes (datatypes) that were created possibly
- The amount of existing classes (datatypes) that were re-modified in this sprint
- Mention that the coordinator GUI was not modified yet for this sprint for the different logins, as we first decided to finalize both biometric and symmetric logins for the administrator UI and then for the 4th sprint, we can simply transpose these changes to the coordinator UI with very minor differences.

Technical:
- scene builder further used for the GUI changes for the login page of the administrator
- also new tabs for the quality insurance variant (ask Julien about this)
- Mention the errors that arose after one of the pushes concerning the biometric login and that it was fixed together with the team shortly after
