### ISSUE TITLE
Implementation (Quality Insurance - Humans)

### ISSUE THREAD

**Issue by Haotzzz** [aryobarzan/UL-SE-2018-g05#41]

**Comment by lrhel** [comment]
* [ ] oeAddQuestion
    * [ ] GUI Button
    * [ ] SQL Statement
    * [ ] Server Side
    * [ ] Client Side
    * [ ] System Side
* [ ] oeDeleteQuestion
    * [ ] GUI Button
    * [ ] SQL Statement
    * [ ] Server Side
    * [ ] Client Side
    * [ ] System Side
* [ ] oeShowAnswer
    * [ ] GUI Button
    * [ ] SQL Statement
    * [ ] Server Side
    * [ ] Client Side
    * [ ] System Side
