### ISSUE TITLE
Symmetric Login additionnal message from ieMessage

### ISSUE THREAD

**Issue by lrhel** [aryobarzan/UL-SE-2018-g05#61]
By testing the Symmetric Login module, using the following credential
username: icrashadmin
nonce: 1
Even after a successful login (I can access the admin panel), I get the following ieMessage
```
Wrong identification information! Please try again ...
Intrusion tentative !
```

**Comment by aryobarzan** [comment]
Problem could be recreated, however the source of the issue has not been determined yet.
High estimated story points for this as a possible rewrite of the encryption/decryption may be required.
